language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"

before_install:
  - docker-compose build
  - docker-compose  up -d

services:
  - docker

script:
  - docker-compose run api npm test
